### ISSUE TITLE
some question about the data_generate file

### ISSUE THREAD

**Issue by laixiaolian** [kpiyush16/learning_sequence_encoders#1]
Thanks for doing the implement of Temperal KG Completion framework.
I want to ask a question about the data_generate : I can't find wikidata_prepare() and test_wikidata_prepare() function in the data_generate.py file. I really want to know how you deal with wikidata and yago data. I’m looking forward to your reply！

**Comment by kpiyush16** [comment]
Hi @laixiaolian, I've added the file [wikidata_generate.py](https://github.com/kpiyush16/learning_sequence_encoders/blob/master/wikidata_generate.py) which contains the functions you're looking for.
